[2021-08-16 08:43:59,697][MainThread:6600][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 09:26:05,581][Thread-1:6276][task_id:lts.views][views.py:298][INFO][登录成功]
[2021-08-16 09:29:53,801][Thread-2:14028][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:30:02,573][Thread-2:14028][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:30:06,047][Thread-2:14028][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:30:12,353][Thread-2:14028][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:31:22,957][Thread-3:20668][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:33:12,288][Thread-4:1708][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:33:34,106][Thread-4:1708][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:37:50,807][Thread-7:21272][task_id:lts.views][views.py:207][INFO][登录成功]
[2021-08-16 09:38:11,319][Thread-9:21436][task_id:lts.views][views.py:207][INFO][登录成功]
[2021-08-16 09:39:39,409][Thread-11:13720][task_id:lts.views][views.py:265][INFO][登录成功]
[2021-08-16 09:40:09,676][Thread-13:13488][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:40:32,439][MainThread:6600][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 09:40:34,075][MainThread:9280][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 09:41:12,531][MainThread:9280][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 09:41:13,565][MainThread:17376][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 09:41:16,304][Thread-1:3568][task_id:lts.views][views.py:6440][INFO][OperationSystem接口操作成功]
[2021-08-16 09:42:31,865][Thread-2:19516][task_id:lts.views][views.py:6440][INFO][OperationSystem接口操作成功]
[2021-08-16 09:43:39,597][Thread-3:21024][task_id:lts.views][views.py:207][INFO][登录成功]
[2021-08-16 09:50:35,231][MainThread:17376][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 09:50:36,483][MainThread:16204][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 09:54:05,269][Thread-3:13436][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 09:54:11,276][Thread-3:13436][task_id:lts.views][views.py:6447][ERROR][OperationSystem接口操作失败]
[2021-08-16 10:09:51,189][MainThread:16204][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\urls.py changed, reloading.]
[2021-08-16 10:09:52,212][MainThread:20056][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 10:47:13,255][MainThread:20056][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\urls.py changed, reloading.]
[2021-08-16 10:47:14,280][MainThread:21424][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 10:47:22,291][Thread-1:23040][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticOperationSystem]
Traceback (most recent call last):
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py", line 6355, in get
    drs = db.execute_sql(conn, sql)
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\common\db.py", line 45, in execute_sql
    cursor.execute(sql)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1046, 'No database selected')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py", line 6397, in get
    result = json.dumps(result)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'OperationalError' is not JSON serializable
[2021-08-16 10:47:23,383][Thread-1:23040][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticOperationSystem]
Traceback (most recent call last):
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py", line 6355, in get
    drs = db.execute_sql(conn, sql)
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\common\db.py", line 45, in execute_sql
    cursor.execute(sql)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1046, 'No database selected')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py", line 6397, in get
    result = json.dumps(result)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'OperationalError' is not JSON serializable
[2021-08-16 10:47:57,914][Thread-1:23040][task_id:lts.views][views.py:265][INFO][登录成功]
[2021-08-16 10:48:05,891][Thread-3:20936][task_id:django.request][log.py:230][WARNING][Not Found: /logistic/LogisticNoPageProductInfoSearch]
[2021-08-16 10:48:37,144][Thread-5:21924][task_id:lts.views][views.py:207][INFO][登录成功]
[2021-08-16 11:00:25,886][MainThread:21424][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:00:27,857][MainThread:22332][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:01:06,319][MainThread:22332][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:01:07,896][MainThread:14944][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:03:41,589][MainThread:14944][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:03:42,706][MainThread:21100][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:08:21,571][MainThread:21100][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:08:22,754][MainThread:1116][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:08:51,496][MainThread:1116][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:08:52,528][MainThread:21212][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:17:58,935][Thread-2:22744][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticOperationSystem]
Traceback (most recent call last):
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py", line 6355, in get
    drs = db.execute_sql(conn, sql)
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\common\db.py", line 45, in execute_sql
    cursor.execute(sql)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1046, 'No database selected')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py", line 6397, in get
    result = json.dumps(result)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'OperationalError' is not JSON serializable
[2021-08-16 11:18:12,936][Thread-2:22744][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticOperationSystem]
Traceback (most recent call last):
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py", line 6355, in get
    drs = db.execute_sql(conn, sql)
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\common\db.py", line 45, in execute_sql
    cursor.execute(sql)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1046, 'No database selected')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py", line 6397, in get
    result = json.dumps(result)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'OperationalError' is not JSON serializable
[2021-08-16 11:18:18,585][MainThread:21212][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:18:19,627][MainThread:3360][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:18:37,532][MainThread:3360][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:18:38,583][MainThread:23380][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:27:11,157][Thread-1:17644][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticPrintApai]
Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view lts.views.PrintApai didn't return an HttpResponse object. It returned None instead.
[2021-08-16 11:27:25,422][MainThread:23380][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:27:26,464][MainThread:20096][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:29:20,126][Thread-1:20952][task_id:lts.views][views.py:207][INFO][登录成功]
[2021-08-16 11:29:25,292][Thread-2:3772][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticPrintApai]
Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view lts.views.PrintApai didn't return an HttpResponse object. It returned None instead.
[2021-08-16 11:31:49,673][MainThread:20096][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:31:51,000][MainThread:16004][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:31:59,207][MainThread:16004][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:32:00,213][MainThread:23296][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:32:17,266][Thread-1:11304][task_id:lts.views][views.py:207][INFO][登录成功]
[2021-08-16 11:32:34,965][Thread-1:11304][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticPrintApai]
Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view lts.views.PrintApai didn't return an HttpResponse object. It returned None instead.
[2021-08-16 11:33:43,069][MainThread:23296][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:33:44,895][MainThread:22732][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:33:47,979][Thread-1:2144][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticPrintApai]
Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view lts.views.PrintApai didn't return an HttpResponse object. It returned None instead.
[2021-08-16 11:35:41,374][MainThread:22732][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:35:43,141][MainThread:16012][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:35:54,368][Thread-2:7404][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticPrintApai]
Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view lts.views.PrintApai didn't return an HttpResponse object. It returned None instead.
[2021-08-16 11:35:59,609][Thread-3:21192][task_id:django.request][log.py:230][ERROR][Internal Server Error: /logistic/LogisticPrintApai]
Traceback (most recent call last):
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\zhi.zhou\Anaconda3\envs\lts\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view lts.views.PrintApai didn't return an HttpResponse object. It returned None instead.
[2021-08-16 11:36:59,800][MainThread:16012][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:37:00,913][MainThread:22164][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:47:02,896][MainThread:22164][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:47:03,967][MainThread:21256][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:49:26,930][MainThread:21256][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:49:28,745][MainThread:22536][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:52:44,245][MainThread:22536][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:52:45,271][MainThread:24136][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:52:59,128][MainThread:24136][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:53:00,739][MainThread:18080][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 11:53:40,636][MainThread:18080][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 11:53:42,037][MainThread:5728][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:00:39,531][MainThread:5728][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:00:41,117][MainThread:18668][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:00:53,157][MainThread:18668][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:00:54,636][MainThread:23308][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:00:59,535][MainThread:23308][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:01:01,176][MainThread:24448][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:01:12,578][MainThread:24448][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:01:13,833][MainThread:23780][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:01:25,409][MainThread:23780][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:01:26,983][MainThread:24448][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:01:28,583][MainThread:24448][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:01:30,166][MainThread:21248][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:01:40,841][MainThread:21248][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:01:42,907][MainThread:21720][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:01:51,647][MainThread:21720][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:01:52,800][MainThread:23676][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:02:01,941][MainThread:23676][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:02:02,985][MainThread:4200][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:02:12,693][MainThread:4200][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 12:02:13,819][MainThread:21660][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 12:02:36,967][MainThread:21660][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:06:25,601][MainThread:11140][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:06:33,780][MainThread:11140][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:06:35,131][MainThread:24824][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:06:54,013][MainThread:24824][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:06:55,714][MainThread:23608][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:07:33,842][MainThread:23608][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:07:35,072][MainThread:23832][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:07:43,615][MainThread:23832][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:07:45,289][MainThread:21540][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:07:53,819][MainThread:21540][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:07:55,154][MainThread:24656][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:08:00,173][Thread-1:24400][task_id:lts.views][views.py:209][INFO][登录成功]
[2021-08-16 13:08:17,531][MainThread:24656][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:08:18,818][MainThread:23336][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:12:12,365][MainThread:23336][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:12:13,683][MainThread:24996][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:12:20,041][MainThread:24996][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:12:21,345][MainThread:24144][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:12:52,740][Thread-1:23856][task_id:lts.views][views.py:209][INFO][登录成功]
[2021-08-16 13:14:50,139][MainThread:25192][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:15:28,906][MainThread:25192][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:15:30,061][MainThread:25180][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:15:58,101][MainThread:25180][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 13:15:59,153][MainThread:9244][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 13:16:28,882][MainThread:21232][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:10:25,157][MainThread:26168][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:10:44,611][Thread-1:27204][task_id:lts.views][views.py:210][INFO][登录成功]
[2021-08-16 14:20:30,285][MainThread:21872][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:27:40,880][Thread-2:6908][task_id:lts.views][views.py:210][INFO][登录成功]
[2021-08-16 14:29:04,725][MainThread:21872][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 14:29:06,088][MainThread:28532][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:34:20,660][MainThread:28532][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 14:34:22,036][MainThread:29632][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:34:28,064][MainThread:29632][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 14:34:29,234][MainThread:24024][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:34:40,433][Thread-1:29600][task_id:lts.views][views.py:210][INFO][登录成功]
[2021-08-16 14:40:26,111][MainThread:27008][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:41:50,921][MainThread:27008][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\logistic_tracking_system\settings.py changed, reloading.]
[2021-08-16 14:41:51,967][MainThread:26072][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:42:06,578][Thread-1:19604][task_id:lts.views][views.py:210][INFO][登录成功]
[2021-08-16 14:49:57,840][MainThread:26072][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 14:49:59,230][MainThread:26208][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
[2021-08-16 14:51:34,904][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:35,486][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:37,556][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:38,154][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:38,770][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:39,386][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:39,988][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:40,605][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:41,205][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:41,824][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:42,422][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:43,038][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:43,640][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:44,257][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:44,876][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:45,490][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:46,083][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:46,708][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:47,314][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:47,927][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:48,526][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:49,127][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:49,730][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:50,345][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:50,945][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:51,546][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:52,147][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:52,747][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:53,349][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:51:53,952][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:52:17,681][Thread-1:1332][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-08-16 14:55:25,465][Thread-4:24004][task_id:lts.views][views.py:301][INFO][登录成功]
[2021-08-16 15:02:43,619][MainThread:26208][task_id:django.utils.autoreload][autoreload.py:251][INFO][D:\zhouzhi\gitlit_code\logistic_tracking_system\logistic_tracking_system\lts\views.py changed, reloading.]
[2021-08-16 15:02:44,686][MainThread:6696][task_id:django.utils.autoreload][autoreload.py:637][INFO][Watching for file changes with StatReloader]
